### ISSUE TITLE
Change research method to (N-way ANOVA) + conceptual model as picture in README.md

### ISSUE THREAD

**Issue by sannevanettinger** [sannevanettinger/Airbnb-vs.-Corona-Pandemic#39]

**Comment by Demivandepol** [comment]
The conceptual model for the research: 
![Conceptual-model-2-Airbnb-UK](https://user-images.githubusercontent.com/89737678/158207922-a82dcbc9-23d1-4146-9553-58ede7cbc343.PNG)

**Comment by Demivandepol** [comment]
![directory-tree-16-3-2022](https://user-images.githubusercontent.com/89737678/158614172-2f771d7f-1093-41ec-af09-9c1a9fff53ca.PNG)
