### ISSUE TITLE
Fill READme file with all the collaborations and text in the three datafiles, short manual of using the codes 

### ISSUE THREAD

**Issue by sannevanettinger** [sannevanettinger/Airbnb-vs.-Corona-Pandemic#42]

**Comment by Demivandepol** [comment]
![Summary-statistics-BRISTOL](https://user-images.githubusercontent.com/89737678/157626252-edf4a0f4-b5f2-44a4-bcff-6fa6a4e77a7d.PNG)
![Summary-statistics-GREAT-MANCHESTER](https://user-images.githubusercontent.com/89737678/157626257-bd2d93ab-6610-4c8c-9431-ce0efe931d6d.PNG)
![Summary-statistics-LONDON](https://user-images.githubusercontent.com/89737678/157626260-de898dd6-eab6-41fc-923c-95713a75a8dc.PNG)
![Summary-statistics-OVERALL](https://user-images.githubusercontent.com/89737678/157626262-9ee6c5f2-0145-4818-9e4d-4748708dd713.PNG)

**Comment by Demivandepol** [comment]
![Summary-statistics-OVERALL-small](https://user-images.githubusercontent.com/89737678/157667408-d26551bb-e5df-4131-8567-a6e6f810ecd5.PNG)

**Comment by Demivandepol** [comment]
Adjusted/improved summary statistics!! Right number of observations this time.
![Summary-statistics-BRISTOL-new](https://user-images.githubusercontent.com/89737678/157851971-8a44ef13-51fc-45a5-a6ef-174a070f7734.PNG)
![Summary-statistics-GREAT-MANCHESTER-new](https://user-images.githubusercontent.com/89737678/157851979-fdf7e165-e833-47f3-ab5e-eff2c4a5b229.PNG)
![Summary-statistics-LONDON-new](https://user-images.githubusercontent.com/89737678/157851980-6b6d0906-5875-4720-9529-bb98b7ebd294.PNG)
![Summary-statistics-OVERALL-small-new](https://user-images.githubusercontent.com/89737678/157851982-28924d72-e02f-4203-a201-834337a718ec.PNG)
