### ISSUE TITLE
Transform Preparation Rmd file to R file

### ISSUE THREAD

**Issue by jjacobs123** [sannevanettinger/Airbnb-vs.-Corona-Pandemic#45]

**Comment by Demivandepol** [comment]
Not necessary! The exploration statistics - the summary statistics - need to be in an RMarkdown file, for a clear overview of the statistics. See website Hannes: https://dprep.hannesdatta.com/docs/course/project/grading_details/

"Meaningful RMarkdown reports for (types of) raw data/input files are created, which allow potential users of your repository to understand the content of such files, and the definition of variables. The RMarkdown reports are properly formatted, rendered as HTML or PDF files, and feature information in a variety of modes (e.g., running text, tables, or figures). The rendered Markdown files are “publication-ready” - i.e., code that is not relevant to understanding the data or warning messages is hidden."
