### ISSUE TITLE
Plot the data over time for review_score and num_listings

### ISSUE THREAD

**Issue by ghost** [sannevanettinger/Airbnb-vs.-Corona-Pandemic#52]
Use the mean of the variables per quarter and try to plot this data over time.

**Comment by Demivandepol** [comment]
![plot_number_of_listings](https://user-images.githubusercontent.com/89737678/158396862-3da1acfd-0479-4864-a6ae-3e8e0cb6fe19.jpeg)
![plot_review_score](https://user-images.githubusercontent.com/89737678/158396868-4ce77f28-7342-45f0-b3f2-abcd707825bf.jpeg)
